# Generated by Django 5.2.10 on 2026-01-16 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='로그인 ID')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='전화번호 인증 여부')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='전화번호 인증 시간')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
            ],
            options={
                'verbose_name': '인증 사용자',
                'verbose_name_plural': '인증 사용자들',
                'db_table': 'auth_users',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=10, verbose_name='성별')),
                ('height', models.IntegerField(verbose_name='키(cm)')),
                ('mbti', models.CharField(max_length=4, verbose_name='MBTI')),
                ('personality', models.JSONField(default=list, verbose_name='성격 유형 리스트')),
                ('interests', models.JSONField(default=list, verbose_name='관심사 리스트')),
                ('matching_consent', models.BooleanField(default=False, verbose_name='매칭 동의')),
                ('service_active', models.BooleanField(default=True, verbose_name='서비스 활성화')),
                ('consent_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='동의 업데이트 시간')),
                ('matchable_count', models.IntegerField(default=0, verbose_name='이상형 조건에 부합하는 인원 수')),
                ('last_count_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 카운트 업데이트 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='프로필 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='프로필 수정 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='인증 사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='IdealTypeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_min', models.IntegerField(verbose_name='최소 키(cm)')),
                ('height_max', models.IntegerField(verbose_name='최대 키(cm)')),
                ('age_min', models.IntegerField(verbose_name='최소 나이')),
                ('age_max', models.IntegerField(verbose_name='최대 나이')),
                ('preferred_mbti', models.JSONField(default=list, verbose_name='선호 MBTI 리스트')),
                ('preferred_personality', models.JSONField(default=list, verbose_name='선호 성격 유형 리스트')),
                ('preferred_interests', models.JSONField(default=list, verbose_name='선호 관심사 리스트')),
                ('match_threshold', models.IntegerField(default=3, verbose_name='매칭 임계값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ideal_type_profile', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이상형 프로필',
                'verbose_name_plural': '이상형 프로필들',
                'db_table': 'ideal_type_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 위치',
                'verbose_name_plural': '사용자 위치들',
                'db_table': 'user_locations',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='user_locati_latitud_ecfe0e_idx')],
            },
        ),
    ]
