# Generated by Django 6.0.1 on 2026-01-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='스태프 권한'),
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='슈퍼유저 권한'),
        ),
    ]
