# Generated by Django 6.0.1 on 2026-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authuser_is_active_authuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealtypeprofile',
            name='preferred_mbti',
            field=models.JSONField(blank=True, default=list, verbose_name='선호 MBTI 리스트'),
        ),
    ]
