# Generated by Django 6.0.1 on 2026-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_idealtypeprofile_preferred_mbti'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealtypeprofile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], help_text='사용자의 반대 성별로 자동 설정됩니다', max_length=10, null=True, verbose_name='선호 성별'),
        ),
    ]
