# Generated by Django 6.0.1 on 2026-01-17 13:48

from django.db import migrations


def populate_preferred_gender(apps, schema_editor):
    """기존 이상형 프로필에 preferred_gender 자동 설정"""
    IdealTypeProfile = apps.get_model('users', 'IdealTypeProfile')
    
    for ideal_type in IdealTypeProfile.objects.filter(preferred_gender__isnull=True):
        # 사용자의 성별을 가져와서 반대 성별로 설정
        user_gender = ideal_type.user.gender
        opposite_gender = 'F' if user_gender == 'M' else 'M'
        ideal_type.preferred_gender = opposite_gender
        ideal_type.save()
        print(f'✅ 이상형 프로필 ID {ideal_type.id}: {user_gender} → 성별 {opposite_gender} 설정')


def reverse_populate_preferred_gender(apps, schema_editor):
    """역방향 마이그레이션 (필요시)"""
    IdealTypeProfile = apps.get_model('users', 'IdealTypeProfile')
    IdealTypeProfile.objects.filter(preferred_gender__isnull=False).update(preferred_gender=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_idealtypeprofile_preferred_gender'),
    ]

    operations = [
        migrations.RunPython(populate_preferred_gender, reverse_populate_preferred_gender),
    ]
