# Generated by Django 6.0.1 on 2026-01-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_make_email_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='idealtypeprofile',
            name='preferred_gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('A', '모두')], default='A', max_length=1, verbose_name='선호 성별'),
        ),
    ]
