# Generated by Django 5.2.10 on 2026-01-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_idealtypeprofile_preferred_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="idealtypeprofile",
            name="priority_1",
            field=models.CharField(
                blank=True,
                choices=[("mbti", "MBTI"), ("personality", "성격"), ("interests", "관심사")],
                max_length=20,
                null=True,
                verbose_name="1순위 중요 항목",
            ),
        ),
        migrations.AddField(
            model_name="idealtypeprofile",
            name="priority_2",
            field=models.CharField(
                blank=True,
                choices=[("mbti", "MBTI"), ("personality", "성격"), ("interests", "관심사")],
                max_length=20,
                null=True,
                verbose_name="2순위 중요 항목",
            ),
        ),
        migrations.AddField(
            model_name="idealtypeprofile",
            name="priority_3",
            field=models.CharField(
                blank=True,
                choices=[("mbti", "MBTI"), ("personality", "성격"), ("interests", "관심사")],
                max_length=20,
                null=True,
                verbose_name="3순위 중요 항목",
            ),
        ),
    ]
