# Generated by Django 6.0.1 on 2026-01-17 13:54

from django.db import migrations


def convert_gender_to_array(apps, schema_editor):
    """기존 CharField 성별 데이터를 JSONField 배열로 변환"""
    IdealTypeProfile = apps.get_model('users', 'IdealTypeProfile')
    
    # Raw SQL로 직접 변환 (CharField -> JSON 배열)
    from django.db import connection
    with connection.cursor() as cursor:
        # PostgreSQL에서 CharField 값을 JSON 배열로 변환
        cursor.execute("""
            UPDATE ideal_type_profiles
            SET preferred_gender = CASE
                WHEN preferred_gender = 'M' THEN '["M"]'::jsonb
                WHEN preferred_gender = 'F' THEN '["F"]'::jsonb
                ELSE '[]'::jsonb
            END
            WHERE preferred_gender IS NOT NULL;
        """)
        print(f'✅ 기존 성별 데이터를 배열로 변환 완료')


def reverse_convert_gender_to_array(apps, schema_editor):
    """역방향 마이그레이션 (필요시)"""
    IdealTypeProfile = apps.get_model('users', 'IdealTypeProfile')
    from django.db import connection
    with connection.cursor() as cursor:
        # JSON 배열에서 첫 번째 값을 CharField로 변환
        cursor.execute("""
            UPDATE ideal_type_profiles
            SET preferred_gender = CASE
                WHEN preferred_gender::text LIKE '%"M"%' THEN 'M'
                WHEN preferred_gender::text LIKE '%"F"%' THEN 'F'
                ELSE NULL
            END
            WHERE preferred_gender IS NOT NULL;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_populate_preferred_gender'),
    ]

    operations = [
        migrations.RunPython(convert_gender_to_array, reverse_convert_gender_to_array),
    ]
