# Generated by Django 6.0.1 on 2026-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_idealtypeprofile_preferred_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealtypeprofile',
            name='preferred_gender',
            field=models.JSONField(default=list, help_text='선호하는 성별을 선택하세요 (예: ["M", "F"] 또는 ["M"] 또는 ["F"])', verbose_name='선호 성별 리스트'),
        ),
    ]
