# Generated by Django 5.2.10 on 2026-01-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='사용자1의 위도 (매칭 시점)')),
                ('user1_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='사용자1의 경도 (매칭 시점)')),
                ('user2_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='사용자2의 위도 (매칭 시점)')),
                ('user2_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='사용자2의 경도 (매칭 시점)')),
                ('matched_at', models.DateTimeField(auto_now_add=True, verbose_name='매칭 시간')),
                ('matched_criteria', models.JSONField(default=dict, verbose_name='매칭된 조건')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user1', to='users.user', verbose_name='사용자 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_user2', to='users.user', verbose_name='사용자 2')),
            ],
            options={
                'verbose_name': '매칭',
                'verbose_name_plural': '매칭들',
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_entered_at', models.DateTimeField(blank=True, null=True, verbose_name='boundary 진입 시간')),
                ('boundary_exited_at', models.DateTimeField(blank=True, null=True, verbose_name='boundary 이탈 시간')),
                ('is_active', models.BooleanField(default=False, verbose_name='알림 활성화 여부')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matching.match', verbose_name='매칭')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user', verbose_name='사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
                'db_table': 'notifications',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'matched_at'], name='matches_user1_i_61b20a_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'matched_at'], name='matches_user2_i_6ab38f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_66b334_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'match'], name='notificatio_user_id_d8e596_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('user', 'match')},
        ),
    ]
