# Generated by Django 5.2.10 on 2026-01-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
        ('users', '0004_make_email_not_null'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_d8e596_idx',
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='생성 시간'),
        ),
        migrations.AddField(
            model_name='notification',
            name='device_type',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10, null=True, verbose_name='디바이스 타입'),
        ),
        migrations.AddField(
            model_name='notification',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='FCM 토큰'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='업데이트 시간'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matching.match', verbose_name='매칭'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'fcm_token'], name='notificatio_user_id_0e64cd_idx'),
        ),
    ]
