# Generated by Django 5.2.10 on 2026-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "matching",
            "0002_remove_notification_notificatio_user_id_d8e596_idx_and_more",
        ),
        ("users", "0006_idealtypeprofile_priority_1_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "match"], name="notificatio_user_id_d8e596_idx"
            ),
        ),
    ]
