# Generated by Django 6.0.1 on 2026-01-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_remove_notification_notificatio_user_id_d8e596_idx_and_more'),
        ('users', '0005_idealtypeprofile_preferred_gender'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'match'], name='notificatio_user_id_d8e596_idx'),
        ),
    ]
