# Generated by Django 5.2.10 on 2026-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0003_notification_notificatio_user_id_d8e596_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="match_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="매칭 점수 (0.00 ~ 100.00)",
                max_digits=5,
                null=True,
                verbose_name="매칭 점수",
            ),
        ),
    ]
